version: '3'
services:
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx
    volumes:
    - ./src/:/var/www
    ports:
    - "8080:80"
    - "8090:8090"
    depends_on:
    - php-fpm

  php-fpm:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/php-fpm
    volumes:
    - ./src/:/var/www
    depends_on:
    - mysql
    environment:
      XDEBUG_CONFIG: "remote_enable=1"
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=Docker"

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
        - "33061:3306"
    environment:
      - MYSQL_USER="root"
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
        - ./MySQL:/var/lib/mysql

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"

        links:
            - mysql:db
#  node:
#    build:
#      dockerfile: ./Dockerfile
#      context: ./docker/node
#    #    ports:
#    #    - 8080:8080
#    volumes:
#    - ./src/:/var/www
#    - ./root:/root
#    - modules:/var/www/node_modules
#    tty: true
#    working_dir: /var/www
volumes:
  data:
    external: true
  modules:
